# Generated by cpp11: do not edit by hand

sinba_conditionals <- function(anc, desc, st, lengths, cond, first_age, second_age, root_Q, semi_Q, Q) {
  .Call(`_sinba_sinba_conditionals`, anc, desc, st, lengths, cond, first_age, second_age, root_Q, semi_Q, Q)
}
